# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0846b2e278880e59c6931812e7c17d36aefc281312955821f0633c0222c5a0277d63eac6c2bcb84c14ce2c875cd821e56864e1c1e013e2fc0bc54d6f9ada7903

test:
  secret_key_base: c8951a9335b3590bb5e6e625f35ca653056e96b01ddbdf6d79c0a7877d2fd698f2f800bbb38f8dda63568c3db10a6bec95cf23205a0e077e0347cfc41438f691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
